name: rakkess CI
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.26.x', '1.27.x']
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:

    - name: Check out code
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: ${{ matrix.go }}

    - name: Verify go.mod is sane
      run: go mod tidy && git diff --exit-code -- go.mod go.sum

    - name: Run code lint
      if: matrix.os == 'ubuntu-latest' && matrix.go == '1.27.x'
      run: make lint

    - name: Install dependencies
      run: go mod download

    - name: Run unit tests
      run: |
        set -euo pipefail
        make test
        make coverage
        make race
        make vet

    - uses: codecov/codecov-action@v7
      name: Upload coverage to codecov.io
      if: matrix.os == 'ubuntu-latest' && matrix.go == '1.27.x'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./out/coverage.txt

    - name: Verify build
      run: make dev

    - name: Check Go vulnerabilities
      if: matrix.os == 'ubuntu-latest' && matrix.go == '1.27.x'
      run: go run golang.org/x/vuln/cmd/govulncheck@v1.8.0 ./...

    - name: Cross-compile release binaries
      if: matrix.os == 'ubuntu-latest' && matrix.go == '1.27.x'
      run: make build-rakkess build-access-matrix

    - name: Make binaries
      if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest' && matrix.go == '1.27.x'
      run: |
        set -euo pipefail
        sudo apt update
        sudo apt install -y upx
        make deploy

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest' && matrix.go == '1.27.x'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload binaries to release
      if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest' && matrix.go == '1.27.x'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # hacky glob pattern because this does not accept multiple patterns
        file: out/{access-matrix,rakkess}-{amd64,arm64}-*.{tar,zip}*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

    - name: Update new version in krew-index
      if: github.repository == 'corneliusweig/rakkess' && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest' && matrix.go == '1.27.x'
      uses: rajatjindal/krew-release-bot@v0.0.39
      with:
        krew_template_file: hack/access-matrix.yaml
